[package]
name = "klavaro"
version = "1.0.0"
edition = "2021"
description = "Print your current xkb_layout in Sway."
license = "GPL-3.0-or-later"
repository = "https://github.com/Fierthraix/klavaro"

[dependencies]
swayipc = "3.0.1"
